services:
  - type: web
    name: brasil-mx
    runtime: docker
    repo: https://github.com/danfelito/brasil-mx
    branch: main
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /
    autoDeployTrigger: commit
    envVars:
      - key: NODE_ENV
        value: production
      - key: HOSTNAME
        value: 0.0.0.0
      - key: PORT
        value: 10000
